[programs.mainnet]
vovo = "EHanF38MZdyk2GBxu7uZn5MZzYGJxTnN9sCFRZvNgBb6"
[programs.devnet]
vovo = "EHanF38MZdyk2GBxu7uZn5MZzYGJxTnN9sCFRZvNgBb6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./test-keypair.json"

[scripts]
test-ts = "ts-mocha -p ./tsconfig.json -t 1000000 tests/test_ts.ts"
test-devnet = "ts-mocha -p ./tsconfig.json -t 1000000 tests/devnet-test.ts"
test-create = "ts-mocha -p ./tsconfig.json -t 1000000 tests/mainnet-test-create.ts"
test-deposit = "ts-mocha -p ./tsconfig.json -t 1000000 tests/mainnet-test-deposit.ts"
test-earn = "ts-mocha -p ./tsconfig.json -t 1000000 tests/mainnet-test-earn.ts"
test-poke = "ts-mocha -p ./tsconfig.json -t 1000000 tests/mainnet-test-poke.ts"
test-withdraw = "ts-mocha -p ./tsconfig.json -t 1000000 tests/mainnet-test-withdraw.ts"